# Generated by Django 3.1.5 on 2021-03-30 15:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/default/profile.png', storage=django.core.files.storage.FileSystemStorage(location='/Users/husubayli/Desktop/Documents/Repos/freelance/tech.az/media'), upload_to='users_images'),
        ),
    ]
