version: '3.1'

services: 
    postgres:
        image: postgres:9.6.6
        restart: always
        volumes:
            - ../pgdb/:/var/lib/postgresql/
        ports:
            - "5434:5432"
        env_file: ../.env

