version: '3.1'

services: 
    postgres:
        image: postgres
        restart: always
        volumes:
            - ../pgdb/:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        env_file: ../.env

