# Generated by Django 3.1.5 on 2021-03-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210322_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='join',
            options={'verbose_name': 'Join', 'verbose_name_plural': 'Joins'},
        ),
    ]
